### ISSUE TITLE
No subtraction in log semiring

### ISSUE THREAD

**Issue by jyuhuan** [mgormley/pacaya#3]
In [line 48 of `ExpectedRecall.java`](https://github.com/mgormley/pacaya/blob/master/src/main/java/edu/jhu/pacaya/gm/train/ExpectedRecall.java#L48), a subtraction is performed. If the algebra in use is `LogSemiring`, there will almost always be an illegal state exception thrown, saying that

> x must be >= y

The problem originates from [line 63 of `LogSemiring.java`](https://github.com/mgormley/pacaya/blob/master/src/main/java/edu/jhu/pacaya/util/semiring/LogSemiring.java#L63). The `minus` method of `LogSemiring` calls `FastMath.logSubtract(x,y)`, which requires `x >= y`.

In `ExpectedRecall.java`, `x` (i.e., the variable `expectedRecall`) is initialized to be the zero of the algebra, and `y` is a belief. The exception will be thrown almost every time due `y` is usually greater than the zero. 

Mathematically speaking, subtraction does not exist in a **semi**ring. Is it intended that only algebras like a real ring should be used to perform ERMA training?

**Comment by mgormley** [comment]
As your comment noted, it doesn't actually make sense for a _semiring_ to have a subtract method. Further, the LogSemiring can only represent non-negative numbers. That's why the class is called LogSemiring and not LogAlgebra. However, there are certain situations (e.g. the ProjDepTreeFactor) where we can guarantee that the subtraction won't go negative and it's valid to use this semiring. 

The ExpectedRecall objective is not one of those cases: we must use an algebra that can represent both positive and negative values. [LogSignAlgebra](https://github.com/mgormley/pacaya/blob/fc89a36cc08bc6852612d01c4f77869e32c1be41/src/main/java/edu/jhu/pacaya/util/semiring/LogSignAlgebra.java) addresses exactly this issue. See [Li & Eisner (2009)](http://www.aclweb.org/anthology/D09-1005) for a description of this semiring. This is the same semiring that was used in [Gormley et al. (2015)](https://www.aclweb.org/anthology/Q/Q15/Q15-1035.pdf). The short summary is that it uses a single bit to represent the sign of the number and the remaining bits to represent the log of the absolute value of that number.
